# Copyright (c) 2025, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

"left_hip_pitch_joint": 0
"right_hip_pitch_joint": 1
"waist_yaw_joint": 2
"left_hip_roll_joint": 3
"right_hip_roll_joint": 4
"waist_roll_joint": 5
"left_hip_yaw_joint": 6
"right_hip_yaw_joint": 7
"waist_pitch_joint": 8
"left_knee_joint": 9
"right_knee_joint": 10
"left_shoulder_pitch_joint": 11
"right_shoulder_pitch_joint": 12
"left_ankle_pitch_joint": 13
"right_ankle_pitch_joint": 14
"left_shoulder_roll_joint": 15
"right_shoulder_roll_joint": 16
"left_ankle_roll_joint": 17
"right_ankle_roll_joint": 18
"left_shoulder_yaw_joint": 19
"right_shoulder_yaw_joint": 20
"left_elbow_joint": 21
"right_elbow_joint": 22
"left_wrist_roll_joint": 23
"right_wrist_roll_joint": 24
"left_wrist_pitch_joint": 25
"right_wrist_pitch_joint": 26
"left_wrist_yaw_joint": 27
"right_wrist_yaw_joint": 28
"L_index_proximal_joint": 29
"L_middle_proximal_joint": 30
"L_pinky_proximal_joint": 31
"L_ring_proximal_joint": 32
"L_thumb_proximal_yaw_joint": 33
"R_index_proximal_joint": 34
"R_middle_proximal_joint": 35
"R_pinky_proximal_joint": 36
"R_ring_proximal_joint": 37
"R_thumb_proximal_yaw_joint": 38
"L_index_intermediate_joint": 39
"L_middle_intermediate_joint": 40
"L_pinky_intermediate_joint": 41
"L_ring_intermediate_joint": 42
"L_thumb_proximal_pitch_joint": 43
"R_index_intermediate_joint": 44
"R_middle_intermediate_joint": 45
"R_pinky_intermediate_joint": 46
"R_ring_intermediate_joint": 47
"R_thumb_proximal_pitch_joint": 48
"L_thumb_intermediate_joint": 49
"L_thumb_distal_joint": 50
"R_thumb_intermediate_joint": 51
"R_thumb_distal_joint": 52
